# Generated by Django 2.0 on 2018-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='telegram_chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
