# Generated by Django 2.0 on 2018-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_auto_20180512_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='avito_id',
            field=models.IntegerField(unique=True),
        ),
    ]
