# Generated by Django 2.0 on 2018-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_auto_20180512_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cmd',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
