# Generated by Django 2.0 on 2018-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0005_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
