# Generated by Django 2.0 on 2018-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0006_auto_20180512_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
